name: test-build-examples

on: push

jobs:
  build:
    strategy:
      matrix:
        NIM_VER: [1.0.2, 1.0.6, 1.2.0, latest]
        OS_VER: [ubuntu, alpine]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test build examples
      run: >
        docker run -v `pwd`:/usr/src/app -w /usr/src/app/examples
        nimlang/nim:${{ matrix.NIM_VER }}-${{ matrix.OS_VER }}
        nimble build -y
